name: On-demand self-hosted AWS EC2 runner for GitHub Actions
description: GitHub Action for automatic creation and registration AWS EC2 instance as a GitHub Actions self-hosted runner.
author: Volodymyr Machula
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: false
  github-app-private-key:
    description: >-
      To avoid using a PAT token a Github App with 'repo' scope can be used.
      https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps
    required: false
  github-app-id:
    description: >-
      If using a Github App to generate the token for runner registration, then the Github App Id is needed.
    required: false
  ec2-image-id:
    description: >-
      EC2 Image Id (AMI). The new runner will be launched from this image.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 Instance Type. 
      This input is required if you use the 'start' mode.
    required: false
  subnet-id:
    description: >-
      VPC Subnet Id. The subnet should belong to the same VPC as the specified security group.
      This input is required if you use the 'start' mode.
    required: false
  security-group-id:
    description: >-
      EC2 Security Group Id. 
      The security group should belong to the same VPC as the specified subnet.
      The runner doesn't require any inbound traffic. However, outbound traffic should be allowed.
      This input is required if you use the 'start' mode.
    required: false
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used to remove the runner from GitHub when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  iam-role-name:
    description: >-
      IAM Role Name to attach to the created EC2 instance.
      This requires additional permissions on the AWS role used to launch instances.
    required: false
  aws-resource-tags:
    description: >-
      Tags to attach to the launched EC2 instance and volume.
      This must be a stringified array of AWS Tag objects, with both Key and Value fields,
      for example: '[{"Key": "TagKey1", "Value": "TagValue1"}, {"Key": "TagKey2", "Value": "TagValue2"}]'
    required: false
    default: '[]'
  runner-home-dir:
    description: >-
      Directory that contains actions-runner software and scripts. E.g. /home/runner/actions-runner.
    required: false
  run-as-service-with-user:
    description: >-
      Start the runner as a service using the user account. 
      If left as default this will start the service using ./run.sh (which will run with root permissions).
      Otherwise this will start the service using:
        ./svc.sh install <user>
        ./svc.sh start
    required: false
    default: 'root'
  leave-ec2-instance-running:
    description: >-
      When stop mode is used only deregister the runner in Github and leave the instace running instead of terminating it.
    required: false    
    default: false
outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
runs:
  using: node16
  main: ./dist/index.js
